### ISSUE TITLE
Sellers marked as favorites (when not favorite)

### ISSUE THREAD

**Issue by wangahrah** [anarchyincubator/eggslist-backend#30]
![image](https://user-images.githubusercontent.com/1247276/192160858-5afef5ad-7e5e-401d-967c-1a1824b47f5f.png)
![image](https://user-images.githubusercontent.com/1247276/192160883-2e3aab65-fb07-4e54-aa89-b2b6ec22641f.png)
My only favorite is NICK, but BOBBY and JOHN show up as favorites in "view all listings"

**Comment by fedorgrab** [comment]
Just checking up, I think you mixed up "verified seller" status sign with "favorite seller" status sign as I can see on these pictures that Bobby and John are verified seller, but not favorite sellers.
