### ISSUE TITLE
Mobile item management

### ISSUE THREAD

**Issue by wangahrah** [anarchyincubator/eggslist-backend#52]
On mobile, from profile, we cannot edit / hide listings etc as there is no 'hover' to bring up the menu

**Comment by fedorgrab** [comment]
To proceed with that you need to open the listing itself as it's impossible to use hover on mobile.

**Comment by wangahrah** [comment]
gotcha...this is masked by issue 51 for me where item will not load when clicked from my profile, at least on mobile, can't check on PC right now.

**Comment by wangahrah** [comment]
Closing as when I can load the  item properly it works
